name: rtl-sdr-pr

channels:
    - conda-forge
    - intel

dependencies:
    - black>=21.7b0,<22.0
    - cupy>=9.2.0,<10.0.0
    - flake8>=3.9.2,<4.0.0
    - intel:intelpython3_core>=v2021.3.1
    - intel:numpy>=1.20.0,<2.0.0
    - intel:python>=3.7,<3.10
    - intel:scipy>=1.6.0,<2.0.0
    - ipykernel>=6.0.3,<7.0.0
    - ipympl>=0.7.0,<0.8.0
    - jupyter>=1.0.0,<2.0.0
    - matplotlib>=3.4.2,<4.0.0
    - nbstripout>=0.5.0,<0.6.0
    - nose>=1.3.7,<2.0.0
    - pre-commit>=2.13.0,<3.0.0
    - pytest>=6.2,<7.0
    - rope>=0.19.0,<0.20.0
